export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_LOADING = 'FETCH_LOADING';

export const FETCH_MEDIA_ITEMS = 'FETCH_MEDIA_ITEMS';
export const FETCH_MEDIA_ITEM = 'FETCH_MEDIA_ITEM';

export const FETCH_EPISODES = 'FETCH_EPISODES';
export const FETCH_EPISODE = 'FETCH_EPISODE';
